export { capitalizeText } from './capitalizeText'
export { getPricesByDiscount } from './getPricesByDiscount'
export { delimiter } from './delimiter'
export { comma } from './comma'
export * from './localStorageInstanse'
