export { capitalizeText } from './capitalizeText'
export { getPricesByDiscount } from './getPricesByDiscount'
export * from './localStorageInstanse'
export { workDataInstanse } from './workDataInstanse'
export { addClassnameToElement } from './addClassnameToElement'
export { createElementWithClassName } from './createElementWithClassName'
export { generatePathname } from './generatePathname'
export { toggleClassnameToElement } from './toggleClassnameToElement'
export { removeClassnameToElement } from './removeClassnameToElement '
